[package]
name = "fakeit"
version = "0.1.0"
authors = ["PumpkinSeed <qwer.kocka@gmail.com>"]
edition = "2018"

[[benches]]
name = "fakeit"
harness = false

[dependencies]
rand = "0.6.5"
bencher = "0.1.5"