[package]
name = "fakeit"
version = "0.0.1"
authors = ["PumpkinSeed <qwer.kocka@gmail.com>"]
edition = "2018"
description = "Fake data generator library"
license = "MIT"

[[benches]]
name = "fakeit"
harness = false

[dependencies]
rand = "0.6.5"
bencher = "0.1.5"
libmath = "0.2.1"
chrono = "0.4"